# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b10a3818011ef856ac72e64f6a9e26cb156cf4c01f3a4cfada250ac8c7b5578a2fb0bdae463a83711f7ed7808644ea7f4b6ba1787f4e8f079eb4f9b64b5ea765

test:
  secret_key_base: cb4f6d27f8cfc76ab9b9f4ad998e6927cab3d56303f1de8f79787ef126de057db02462be427f8277d66998a2b7378efd600581c4758e6dea24535c55435ebdb6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
